<?php
// - Extension: warning hook
// - Version: 0.1
// - Author: PivotX Team
// - Email: admin@pivotx.net
// - Site: http://www.pivotx.net
// - Description: This is a simple extension to demonstrate how to add hooks to the warning and messages that are shown by pivot. This extension will display a warning on the dashboard 50% of the times that it is requested, and it will show a message on all pages, also 50% of the time.
// - Date: 2007-09-23
// - Identifier: warning

// Options for hooks are:
// - before_checkwarnings
// - after_checkwarnings
// - before_getwarnings
// - before_getmessages


$this->addHook(
    'messages',
    'after_checkwarnings',
    "hookWarnings"
    );


$this->addHook(
    'messages',
    'before_getmessages',
    "hookMessages"
    );



function hookWarnings() {
    global $PIVOTX;

    if (rand(0,1)) {
        $PIVOTX['messages']->addWarning("This is a random warning, generated by the 'warning extension'.");
    }

}

function hookMessages() {
    global $PIVOTX;

    if (rand(0,1)) {
        $PIVOTX['messages']->addMessage("This is a random message, generated by the 'warning extension'.");
    }

}

?>
