subject: Standaard order mail with debug information [[sitename]]
==========
'status' => [[status]],
'order_id' => [[order_id]],
'order_public_code' => [[order_public_code]],
'order_public_hash' => [[order_public_hash]],
'order_status' => [[order_status]],
'order_datetime' => [[order_datetime]],
'user_name' => [[user_name]],
'user_email' => [[user_email]],
'user_phone' => [[user_phone]],
'user_address' => [[user_address]],
'user_postcode' => [[user_postcode]],
'user_city' => [[user_city]],
'user_country' => [[user_country]],
'user_ip' => [[user_ip]],
'user_hostname' => [[user_hostname]],
'user_browser' => [[user_browser]],
'shipping_handler' => [[shipping_handler]],
'shipping_external_code' => [[shipping_external_code]],
'shipping_status' => [[shipping_status]],
'shipping_datetime' => [[shipping_datetime]],
'payment_provider' => [[payment_provider]],
'payment_external_code' => [[payment_external_code]],
'payment_status' => [[payment_status]],
'payment_datetime' => [[payment_datetime]],
'payment_amount_total' => [[payment_amount_total]],
'payment_message' => [[payment_message]],

order summary:
[[order_summary]]
